# Generated by Django 5.0.6 on 2024-05-30 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('contactInfo', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('contactInfo', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.categories')),
            ],
        ),
        migrations.CreateModel(
            name='PriceChanges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('newPrice', models.DecimalField(decimal_places=4, max_digits=10)),
                ('productID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.product')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=10)),
                ('orderDate', models.DateTimeField(auto_now_add=True)),
                ('customerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.customers')),
                ('productID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.product')),
            ],
        ),
        migrations.CreateModel(
            name='Returns',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=10)),
                ('returnDate', models.DateTimeField(auto_now_add=True)),
                ('orderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.orders')),
                ('productID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.product')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierProduct',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('salePercents', models.DecimalField(decimal_places=4, max_digits=10)),
                ('quantitySale', models.DecimalField(decimal_places=4, max_digits=10)),
                ('productID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.product')),
                ('supplierID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.suppliers')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierOrders',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=10)),
                ('orderDate', models.DateTimeField(auto_now_add=True)),
                ('supplierProductID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.supplierproduct')),
            ],
        ),
        migrations.CreateModel(
            name='SuppliersPriceChanges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('newPrice', models.DecimalField(decimal_places=4, max_digits=10)),
                ('supplierProductID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.supplierproduct')),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('productID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.product')),
            ],
        ),
    ]
