# Generated by Django 5.0.6 on 2024-05-31 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_categories_id_alter_customers_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='returns',
            name='productID',
        ),
        migrations.RemoveField(
            model_name='returns',
            name='quantity',
        ),
    ]
