# Generated by Django 5.0.6 on 2024-05-31 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_suppliersprice_delete_supplierspricechanges'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuppliersPrice1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('newPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('supplierProductID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.supplierproduct')),
            ],
        ),
    ]
