# Generated by Django 5.0.6 on 2024-05-31 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_rename_suppliersprice_supplierspricechanges_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='returns',
            old_name='returnDate',
            new_name='orderDate',
        ),
    ]
